name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmFjMGFhZGEtNjQxMy00MmY5LWFjZGUtMjk1MTRjODUwMWE2IiwidGVuYW50X2lkIjoiZTYzYmQ1NmEzZDQ5MTk5NTc0YTc1NmE5MmMwMjk0YzM1YjJjN2EwM2ZiMzQ0MWE4NTBiMTAxZDhjNWY0OTAyYyIsImludGVybmFsX3NlY3JldCI6ImJhMzFlZmZhLTNlOTItNDhhNi1iYjQ3LTc4NjRiZDE5NTFiZiJ9.NC21AKV36Swqe9rU6zFYq94BsnYJeOZYMkPyxhyfGaw"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1